spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: sanitas
  config:
    import: optional:file:.env[.properties]
  security:
    enabled: false

  # Database Configuration
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Configuration
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect



    # Data Initialization
  sql:
    init:
      mode: always

  # Server Configuration
server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    # Logs de Spring MVC y DispatcherServlet
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: DEBUG